new style script for daily IDA dumps

diff --git a/scripts/ida/tess_ida_bulk_dump b/scripts/ida/tess_ida_bulk_dump
--- a/scripts/ida/tess_ida_bulk_dump
+++ b/scripts/ida/tess_ida_bulk_dump
@@ -16,36 +16,62 @@ ORDER by CAST(substr(name, 6) as decimal) ASC;
 EOF
 }
 
+# get the name from the script name without extensions
+
+help() {
+    name=$(basename ${0%.sh})
+    echo "Usage:"
+    echo "$name -d <database path> -o <dst dir> -m <latest|previous|YYYY-MM> -l <log file path prefix>"
+    echo "Defaults to:"
+    echo "name -d $DEFAULT_DATABASE -o $DEFAULT_DST_DIR -m $DEFAULT_MONTH -l $DEFAULT_LOG_FILE_PREFIX"
+}
+
 # ------------------------------------------------------------------------------- #
 
-TESS_IDA=/usr/local/bin/tess-ida
-
 DEFAULT_DATABASE="/var/dbase/tess.db"
-DEFAULT_REPORTS_DIR="/var/dbase/reports/IDA"
+DEFAULT_DST_DIR="/var/dbase/reports/IDA"
 DEFAULT_MONTH="latest"
+DEFAULT_LOG_FILE_PREFIX=/var/log/ida_daily
 
 TEE=$(which tee)
-
+TESS_IDA=$(which tess-ida)
 LOG_DATE=$(/usr/bin/date +%Y%m%d)
 
-# get the name from the script name without extensions
-name=$(basename ${0%.sh})
 
-# Either the default or the rotated tess.db-* database
-dbase="${1:-$DEFAULT_DATABASE}"
-# wildcard expansion ...
-dbase="$(ls -1 $dbase)"
-
-# Output directory is created if not exists inside the inner script
-out_dir="${2:-$DEFAULT_REPORTS_DIR}"
-
-# Month: either "latest", "previous" or "YYYY-MM"
-month="${3:-$DEFAULT_MONTH}"
+while getopts ":hd:o:m:l:" opt; do
+    case ${opt} in
+    d)
+        dbase="${OPTARG}"
+        ;;
+    o)
+        out_dir="${OPTARG}"
+        ;;
+    m)
+        month="${OPTARG}"
+        ;;
+    l)
+        log_file="${OPTARG}_${LOG_DATE}.log"
+        ;;
+    h)
+        help
+        exit 0
+        ;;
+    :)
+        echo "Option -${OPTARG} requires an argument."
+        exit 1
+        ;;
+    ?)
+        echo "Invalid option: -${OPTARG}."
+        exit 1
+        ;;
+  esac
+done
+shift "$((OPTIND-1))"
 
 
 if  [[ ! -f $dbase || ! -r $dbase ]]; then
-        echo "Database file $dbase does not exists or is not readable." | ${TEE} -a ${LOG_FILE}
-        echo "Exiting" | ${TEE} -a ${LOG_FILE}
+        echo "Database file $dbase does not exists or is not readable." | ${TEE} -a ${log_file}
+        echo "Exiting" | ${TEE} -a ${log_file}
         exit 1
 fi
 
@@ -55,17 +81,17 @@ photometers=$(query_names ${dbase})
 for instrument in $photometers; do
     if [[ "$month" = "latest" ]];
     then
-        echo "Generating latest month IDA file for TESS $instrument under ${out_dir}/${instrument}" | ${TEE} -a ${LOG_FILE}
-        ${TESS_IDA} ${instrument} --log-file ${LOG_FILE} --latest-month -d ${dbase} -o ${out_dir} 
+        echo "Generating latest month IDA file for TESS $instrument under ${out_dir}/${instrument}" | ${TEE} -a ${log_file}
+        ${TESS_IDA} ${instrument} --log-file ${log_file} --latest-month -d ${dbase} -o ${out_dir} 
     elif [[ "$month" = "previous" ]];
     then
-        LOG_FILE="${HOME}/dbase/log/ida_monthly_${LOG_DATE}.log"
-        echo "Generating previous month IDA file for TESS $instrument under ${out_dir}/${instrument}" | ${TEE} -a ${LOG_FILE}
-        ${TESS_IDA} ${instrument} --log-file ${LOG_FILE} --previous-month -d ${dbase} -o ${out_dir}
+        log_file="${HOME}/dbase/log/ida_monthly_${LOG_DATE}.log"
+        echo "Generating previous month IDA file for TESS $instrument under ${out_dir}/${instrument}" | ${TEE} -a ${log_file}
+        ${TESS_IDA} ${instrument} --log-file ${log_file} --previous-month -d ${dbase} -o ${out_dir}
     else
-        LOG_FILE="${HOME}/dbase/log/ida_oneoff_${LOG_DATE}.log"
-        echo "Generating IDA file for TESS $instrument for month $month under ${out_dir}/${instrument}" | ${TEE} -a ${LOG_FILE}
-        ${TESS_IDA} ${instrument} --log-file ${LOG_FILE} --for-month ${month} -d ${dbase} -o ${out_dir}
+        log_file="${HOME}/dbase/log/ida_oneoff_${LOG_DATE}.log"
+        echo "Generating IDA file for TESS $instrument for month $month under ${out_dir}/${instrument}" | ${TEE} -a ${log_file}
+        ${TESS_IDA} ${instrument} --log-file ${log_file} --for-month ${month} -d ${dbase} -o ${out_dir}
     fi
 done
 
